# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Xilinx/Projects/swerling_model_rom/swerling_model_rom.cache/wt [current_project]
set_property parent.project_path C:/Xilinx/Projects/swerling_model_rom/swerling_model_rom.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Xilinx/Projects/swerling_model_rom/swerling_model_rom.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files C:/Xilinx/Projects/swerling_model_rom/mat/hcoe.coe
add_files -quiet C:/Xilinx/Projects/swerling_model_rom/swerling_model_rom.srcs/sources_1/ip/log_fun_65536x16/log_fun_65536x16.dcp
set_property used_in_implementation false [get_files C:/Xilinx/Projects/swerling_model_rom/swerling_model_rom.srcs/sources_1/ip/log_fun_65536x16/log_fun_65536x16.dcp]
add_files -quiet C:/Xilinx/Projects/swerling_model_rom/swerling_model_rom.srcs/sources_1/ip/square_root/square_root.dcp
set_property used_in_implementation false [get_files C:/Xilinx/Projects/swerling_model_rom/swerling_model_rom.srcs/sources_1/ip/square_root/square_root.dcp]
read_vhdl -library xil_defaultlib C:/Xilinx/Projects/swerling_model_rom/swerling_model_rom.srcs/sources_1/new/swerling_model_rom.vhd
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top swerling_model_rom -part xc7a35tcpg236-3


write_checkpoint -force -noxdef swerling_model_rom.dcp

catch { report_utilization -file swerling_model_rom_utilization_synth.rpt -pb swerling_model_rom_utilization_synth.pb }
