clc; clear all; format short; close all;
w = 16; % число бит коэффициентов
%k_scale = (2^(w)); % Максимальный код
N = 2^w;


x = (1:N)/N;
h = log(x); 
h_n = h/max(abs(h));
h_n = h_n*65535;
figure;
plot(x, h_n); grid;

hfileCoeff = fopen('hcoe.coe','w');
fprintf(hfileCoeff,'; XILINX CORE Generator MEM FILE (.COE) File\n');
fprintf(hfileCoeff,'; Generated by MATLAB(R) 14.0\n');
fprintf(hfileCoeff,'; Function is natural log of x\n');
fprintf(hfileCoeff,'memory_initialization_radix = 10;\n');
fprintf(hfileCoeff,'memory_initialization_vector= ' );

for k = 1:N,
    fprintf(hfileCoeff,'%6.0f',abs(h_n(k)));
    if k == N,
        fprintf(hfileCoeff,';'); 
    else
        fprintf(hfileCoeff,' '); 
    end;
end;
fclose(hfileCoeff);

return