# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Xilinx/Projects/swerling_model_rom/swerling_model_rom.srcs/sources_1/ip/square_root/square_root.xci
# IP: The module: 'square_root' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Xilinx/Projects/swerling_model_rom/swerling_model_rom.srcs/sources_1/ip/square_root/square_root_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'square_root'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/Xilinx/Projects/swerling_model_rom/swerling_model_rom.srcs/sources_1/ip/square_root/square_root.xci
# IP: The module: 'square_root' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Xilinx/Projects/swerling_model_rom/swerling_model_rom.srcs/sources_1/ip/square_root/square_root_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'square_root'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
